repos:
- repo: https://github.com/bridgecrewio/checkov.git
  rev: '2.0.1204' # change to tag or sha
  hooks:
    - id: checkov
      verbose: true
      args: [--soft-fail-on LOW]
- repo: https://github.com/bridgecrewio/yor
  rev: 0.1.145
  hooks:
    - id: yor
      name: yor
      entry: yor tag -d
      args: ["."]
      language: golang
      types: [terraform]
      pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: '.*\.(encrypted|pem|tfvars)$'
    - id: mixed-line-ending
      args: [--fix=no]
    - id: trailing-whitespace
      exclude: '.*\.(encrypted|pem)$'
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.72.1
  hooks:
    - id: terraform_fmt
      exclude: '.*/\.terragrunt-cache'
